/* ============================================
   ADAMNOTEVE — Pinterest SEO overlay
   Keyword-optimized titles/descriptions used ONLY by the Pinterest/Google
   product feed (scripts/gen-pinterest-feed.js). The website keeps the witty
   names/descriptions from lib/products.js — this overlay makes the FEED
   searchable on Pinterest (a search engine) without changing the brand voice.

   To add a NEW product: add an entry with its product id below. If a product
   has no entry here, the feed falls back to its lib/products.js name/desc.
   Keep pinTitle <= 100 chars, pinDesc ~150-320 chars, keywords = search phrases.
   Regenerate the feed after editing:  node scripts/gen-pinterest-feed.js
   ============================================ */

const PIN_SEO_LIST = [
{"id":"p1","pinTitle":"Funny Breakup Mug — 'I Dodged a Bullet' Coffee Cup | Divorce Gift for Her 🍎","pinDesc":"A funny breakup gift that says what you're thinking: you dodged a bullet. This petty coffee mug is perfect for a divorce gift for her, a newly-single bestie, or your own villain era morning brew. Microwave-safe, trauma-tested. Sip your closure — add it to your cart.","keywords":["funny breakup mug","breakup gift for her","divorce gift","funny coffee mug","petty gift","villain era gift","single girl gift","dodged a bullet"]},
{"id":"p2","pinTitle":"'Thanks for the Trauma' Hoodie — Funny Breakup Sweatshirt | Villain Era Gift 🍎","pinDesc":"A cozy funny breakup hoodie for your villain era — soft on the outside, salty on the inside. This petty sweatshirt makes a hilarious breakup gift, ex-boyfriend revenge dressing, or self-love comfort wear. Great for divorce healing and hot single winters. Wrap up in it.","keywords":["funny breakup hoodie","villain era outfit","petty sweatshirt","breakup gift","self love hoodie","divorce gift for her","cozy hoodie aesthetic","emotional support hoodie"]},
{"id":"p3","pinTitle":"'Emotionally Unavailable Club' Tee — Funny Single Shirt | Anti Relationship Gift 🍎","pinDesc":"For the emotionally unavailable icon in your life: a funny single-girl shirt with membership perks like solitude, peace, and not texting back. A petty breakup gift, self-love tee, or villain era outfit staple. Great for the freshly single bestie. Join the club — grab yours.","keywords":["funny single shirt","emotionally unavailable","self love tee","villain era outfit","petty quotes shirt","funny breakup shirt","single era","gift for single friend"]},
{"id":"p4","pinTitle":"'We Were a Mistake' Candle — Petty Breakup Gift | Funny Ex Candle 🍎","pinDesc":"Notes of 'I told you so,' vintage regret, and a hint of 'you up?' This funny breakup candle is the pettiest self-care gift for a divorce party, girls' night, or your own healing era. Pick your scent, hand-poured. A hilarious anti-valentine gift for her. Light it and let go.","keywords":["funny breakup candle","petty gift","breakup self care","divorce party gift","anti valentine gift","scented candle gift","villain era decor","gift for her breakup"]},
{"id":"p5","pinTitle":"'Red Flags Were My Aesthetic' Tote Bag — Funny Breakup Gift | Aesthetic Tote 🍎","pinDesc":"Carry your groceries, your trauma, and your entire personality in one bag. This funny tote bag is a petty breakup gift, villain era accessory, and everyday aesthetic tote for the girl who dated red flags on purpose. Great for book club, farmers market, and self-love shopping sprees. Tote your truth.","keywords":["funny tote bag","aesthetic tote bag","breakup gift","red flags","villain era outfit","petty gift for her","canvas tote bag","self love gift"]},
{"id":"p6","pinTitle":"'Closure Is a Myth' Sticker — Petty Breakup Sticker | Laptop Water Bottle Sticker 🍎","pinDesc":"Slap it on your laptop, journal, or your therapist's door. This petty breakup sticker is three sizes of truth for the freshly single, the villain era enthusiast, and the closure-is-a-myth believer. A cute waterproof laptop and water bottle sticker + tiny funny gift. Stick it on and move on.","keywords":["funny sticker","laptop sticker","breakup sticker","water bottle sticker","petty quotes","villain era","aesthetic stickers","self love sticker"]},
{"id":"p8","pinTitle":"'Ghosted' Phone Case — Funny Breakup Phone Case | iPhone & Galaxy Gift 🍎","pinDesc":"For when you're done waiting for the text. This funny ghosted phone case is a petty breakup gift and villain era accessory that fits iPhone 14–17 and Galaxy S23–S26. Perfect for the single bestie, the emotionally unavailable icon, or your own self-love glow-up. Case closed — shop it.","keywords":["funny phone case","breakup gift","ghosted","iphone case aesthetic","petty gift","villain era accessory","galaxy phone case","gift for single friend"]},
{"id":"p9","pinTitle":"'Petty in Pink' Crewneck — Villain Era Sweatshirt | Pink Aesthetic Breakup Gift 🍎","pinDesc":"Soft sweatshirt energy meets sharp-tongue energy. This pink villain era crewneck is a petty breakup gift, self-love staple, and cozy aesthetic sweatshirt for wearing your villain era proudly. Great for the freshly single bestie or your hot-girl healing era. Get petty in pink.","keywords":["villain era outfit","pink crewneck aesthetic","petty sweatshirt","breakup gift for her","self love sweatshirt","funny crewneck","cozy aesthetic outfit","single girl gift"]},
{"id":"p10","pinTitle":"'Toxic Ex Repellent' Candle — Funny Breakup Candle | Petty Divorce Gift 🍎","pinDesc":"Spray-free formula: it's a candle, so it can't actually keep them away — but it smells incredible trying. A funny breakup candle and petty gift for a divorce party, single bestie, or your own healing era. Hand-poured soy, amber jar, five scents, 4oz or 9oz. Light your toxic ex away.","keywords":["funny breakup candle","toxic ex","petty gift","soy candle gift","divorce party gift","breakup self care","anti valentine gift","gift for her"]},
{"id":"p11","pinTitle":"'Single & Salty' Water Bottle — Funny Single Gift | Self Love Water Bottle 🍎","pinDesc":"Stay hydrated. Stay bitter. Stay you. This funny single-girl water bottle holds 17oz of pure self-love and petty energy — a great breakup gift, gym motivation, and villain era accessory for the freshly single bestie. Sip your standards high. Fill up your cart.","keywords":["funny water bottle","single girl gift","self love gift","breakup gift","villain era accessory","aesthetic water bottle","gift for single friend","petty gift"]},
{"id":"p12","pinTitle":"'Cried in the Uber' Crewneck — Funny Breakup Sweatshirt | Relatable Sad Girl Gift 🍎","pinDesc":"A relatable ride down memory lane — the driver said nothing, you said everything. This funny breakup crewneck is a cozy self-love sweatshirt and petty gift for the sad-girl-era bestie, the freshly single, or anyone healing out loud. Cozy up in your feelings. Add to cart.","keywords":["funny breakup sweatshirt","relatable crewneck","sad girl era","self love gift","breakup gift","villain era outfit","cozy aesthetic sweatshirt","gift for best friend breakup"]},
{"id":"p13","pinTitle":"'Self-Care Era' Tee — Self Love Shirt | Healing After Breakup Gift 🍎","pinDesc":"A wearable reminder that you are the love of your own life (sorry, ex). This self-love tee is perfect for your healing era, self-care Sundays, and villain era glow-up — a thoughtful breakup gift for a bestie or yourself. Soft, comfy, quietly petty. Wear your self-care era.","keywords":["self love tee","self care shirt","healing era","breakup gift for her","villain era outfit","aesthetic tshirt","mental health shirt","gift for single friend"]},
{"id":"p14","pinTitle":"'Allergic to Mixed Signals' Hoodie — Funny Dating Hoodie | Petty Breakup Gift 🍎","pinDesc":"If 'wyd' makes you break out in hives, this funny dating hoodie is your antihistamine. A petty breakup gift and villain era staple for the emotionally-done bestie who's over mixed signals and half-texts. Cozy, soft, brutally honest. Cure your situationship — shop the hoodie.","keywords":["funny hoodie","petty quotes hoodie","breakup gift","villain era outfit","mixed signals","funny dating shirt","self love hoodie","gift for single friend"]},
{"id":"p15","pinTitle":"'Block & Move On' Socks — Funny Breakup Socks | Petty Gift for Her 🍎","pinDesc":"Walk away in style with an all-over 'BLOCKED' print, just in case anyone forgets. These funny breakup crew socks are a tiny petty gift, stocking stuffer, and villain era accessory for the bestie who blocks and thrives. Cozy and unbothered. Step into your era — grab a pair.","keywords":["funny socks","breakup gift","petty gift","novelty socks","villain era accessory","stocking stuffer for her","blocked and moved on","gift for single friend"]},
{"id":"p17","pinTitle":"'Salty Single' Tumbler — Funny Single Gift | Insulated Tumbler for Her 🍎","pinDesc":"Insulated tumbler for the freshly single — keeps drinks cold and standards high. This funny single-girl tumbler is a petty breakup gift, villain era desk accessory, and self-love sip companion for the bestie who's salty and thriving. Great for coffee, wine, or spite. Fill it up.","keywords":["funny tumbler","single girl gift","insulated tumbler","breakup gift","self love gift","villain era accessory","aesthetic tumbler","gift for single friend"]},
{"id":"p18","pinTitle":"'Manifest, Don't Text' Journal — Self Love Journal | Breakup Healing Gift 🍎","pinDesc":"A spiral journal for writing things down instead of sending them at 2am. This self-love journal is a healing-era essential and petty breakup gift for manifesting, shadow work, and no-contact accountability. Great for the bestie in her glow-up. Manifest, don't text — start writing.","keywords":["self love journal","breakup healing gift","manifestation journal","no contact","villain era","aesthetic journal","gift for her breakup","self care gift"]},
{"id":"p23","pinTitle":"'Healing Era' Desk Mat — Pink Aesthetic Desk Mat | Self Care Room Decor 🍎","pinDesc":"A big pink desk mat to manifest on — and a soft place to cry over spreadsheets. This aesthetic desk mat is villain era home-office decor, a self-care gift, and petty breakup pick-me-up for the WFH bestie. Great for cute desk setups and healing-era workspaces. Deck out your desk.","keywords":["aesthetic desk mat","pink desk decor","home office aesthetic","breakup self care","villain era decor","cute desk setup","self care gift","aesthetic room decor"]},
{"id":"p25","pinTitle":"'Lost' Tee — Finding Yourself Shirt | Aesthetic Breakup Gift 🍎","pinDesc":"Lost him. Lost the plot. Found a great tee. This minimal strikethrough-wordmark shirt is for your finding-yourself era — a self-love tee, aesthetic staple, and petty breakup gift for the bestie rediscovering herself. Great for villain era and glow-up outfits. Find yourself in it.","keywords":["aesthetic tshirt","self love tee","finding yourself","breakup gift","villain era outfit","minimalist shirt","funny breakup shirt","gift for single friend"]},
{"id":"p26","pinTitle":"Anti-Valentine Cards (6-Pack) — Funny Breakup Cards | Petty Greeting Card Set 🍎","pinDesc":"Six brutally honest cards for every stage of someone else's heartbreak — pick your petty. This anti-valentine card collection is a funny breakup gift, galentine's staple, and petty pick-me-up for a divorcing friend or single bestie. Say the quiet part loud. Send one today.","keywords":["anti valentine gift","funny breakup card","greeting card set","petty gift","divorce gift","galentines gift","funny card for friend","breakup humor"]},
{"id":"p27","pinTitle":"'Emotional Support Beverage' Koozie — Funny Can Cooler | Petty Party Gift 🍎","pinDesc":"Keep your drink cold and your feelings colder. This funny can koozie fits cans and emotional baggage — a petty breakup gift, divorce party favor, and villain era accessory for the bestie who copes with a cold one. Great for bachelorette and single-summer parties. Grab a koozie.","keywords":["funny koozie","can cooler","petty gift","divorce party favor","bachelorette party","emotional support","villain era accessory","funny drink gift"]},
{"id":"p28","pinTitle":"Petty Pet Bandana — Funny Dog Bandana | Breakup Humor Pet Gift 🍎","pinDesc":"Let your pet do the talking with four petty designs that snap onto any collar. This funny dog bandana is a breakup-humor gift for the newly-single pet parent whose dog is now the only loyal one. Great for photoshoots and villain era pet content. Dress the good boy up.","keywords":["funny dog bandana","pet bandana","dog accessories","petty gift","breakup humor","pet parent gift","dog collar bandana","funny pet gift"]},
{"id":"p33","pinTitle":"Heartbreak Bandana — Neon Hearts Bandana | Aesthetic Breakup Accessory 🍎","pinDesc":"All-over neon hearts on a soft bandana — wear your feelings on your head, neck, or wrist. This aesthetic heartbreak bandana is a villain era accessory and petty breakup gift for the bestie styling her sad-girl era. Great for festivals and hot single summer looks. Tie one on.","keywords":["aesthetic bandana","heart bandana","villain era accessory","breakup gift","hair bandana","festival outfit","petty gift","hot single summer"]},
{"id":"p34","pinTitle":"Red Flag Bandana — Funny All-Over Print Bandana | Petty Villain Era Accessory 🍎","pinDesc":"Covered head-to-toe in red flags — finally, on purpose. This funny all-over-print bandana is a petty breakup gift and villain era accessory for the girl who owns her taste in red flags. Great for festivals, hair ties, and hot single summer fits. Fly your flags loud.","keywords":["funny bandana","red flags","villain era accessory","aesthetic bandana","petty gift","breakup humor","festival outfit","hair bandana"]},
{"id":"p29","pinTitle":"Petty Sticker Pack (5) — Funny Breakup Stickers | Laptop Water Bottle Sticker Set 🍎","pinDesc":"Slap your trauma on a water bottle. This kiss-cut, weatherproof sticker pack serves five flavors of petty — perfect for laptops, journals, and hydro flasks. A cute little breakup gift, villain era decor, and stocking stuffer for the single bestie. Five for the price of petty. Grab the pack.","keywords":["funny stickers","sticker pack","laptop stickers","water bottle stickers","breakup gift","petty quotes","aesthetic stickers","villain era"]},
{"id":"p30","pinTitle":"Petty Magnet Set (5) — Funny Fridge Magnets | Breakup Humor Kitchen Decor 🍎","pinDesc":"Decorate the fridge you now have all to yourself. This die-cut magnet set brings five petty designs to your kitchen — a funny breakup gift, villain era decor, and housewarming pick for the newly-single bestie. Great for lockers, whiteboards, and spite. Stick it to the fridge.","keywords":["funny magnets","fridge magnets","breakup gift","petty gift","kitchen decor","villain era decor","housewarming gift","aesthetic magnets"]},
{"id":"p31","pinTitle":"'Thanks for the Trauma' Tee — Funny Breakup Shirt | Petty Bestie Gift 🍎","pinDesc":"Our bestselling trauma, now on a softer, lighter, cheaper tee — same petty, smaller price. This funny breakup shirt is a villain era staple and petty gift for the freshly single bestie. Great for group orders and matching squads on a girls' trip. Wear the trauma. Add to cart.","keywords":["funny breakup shirt","petty quotes shirt","villain era outfit","breakup gift","matching shirts","group order shirts","self love tee","gift for single friend"]},
{"id":"p32","pinTitle":"'Petty in Pink' Tee — Pink Villain Era Shirt | Everyday Petty Gift 🍎","pinDesc":"Pink, petty, and proud — the crewneck classic, now an everyday tee for less. This pink villain era shirt is a self-love staple and petty breakup gift for the bestie in her hot-girl healing era. Great for group orders and matching girls'-trip fits. Get petty in pink — shop now.","keywords":["pink aesthetic shirt","villain era outfit","petty quotes shirt","breakup gift for her","self love tee","matching shirts","group order shirts","single girl gift"]},
{"id":"p35","pinTitle":"adamnot♥eve Logo Tee — Petty Breakup Brand Shirt | Villain Era Staple 🍎","pinDesc":"Wear the brand — the adamnot♥eve wordmark, front and center. This logo tee is a minimal villain era staple, self-love shirt, and petty breakup gift for the bestie living her single era loud and proud. Great for everyday fits and matching squads. Rep the pettiness. Add to cart.","keywords":["aesthetic logo tee","villain era outfit","breakup brand shirt","self love tee","petty gift","minimalist tshirt","matching shirts","single era"]},
{"id":"p36","pinTitle":"'Property of Adamnoteve' Tee — Varsity Breakup Shirt | Heartbreak Dept Gift 🍎","pinDesc":"Varsity-style staple: PROPERTY OF ADAMNOTEVE, Heartbreak Dept. This collegiate breakup shirt is a villain era outfit, self-love tee, and petty gift for the bestie who belongs only to herself now. Great for matching squads and group orders. Claim your era — shop the tee.","keywords":["varsity shirt aesthetic","villain era outfit","breakup gift","self love tee","collegiate tshirt","petty quotes shirt","matching shirts","single era"]},
{"id":"p37","pinTitle":"Bitten Heart Sticker — Cute Breakup Sticker | Petty Laptop Water Bottle Sticker 🍎","pinDesc":"Meet Eve, our bitten heart-apple mascot — slap her on a laptop, water bottle, or your ex's bumper. This cute waterproof breakup sticker is a tiny petty gift and villain era accessory for the freshly single. 'Petty Since the Garden.' Great stocking stuffer. Stick her anywhere.","keywords":["cute sticker","laptop sticker","breakup sticker","water bottle sticker","petty gift","aesthetic stickers","villain era","heart apple"]},
{"id":"p38","pinTitle":"Bitten Heart Magnet — Cute Fridge Magnet | Petty Breakup Kitchen Decor 🍎","pinDesc":"Eve, our bitten heart-apple mascot, holding down the fridge you now own outright. This die-cut flexible magnet is a cute breakup gift, villain era kitchen decor, and petty pick-me-up for the newly-single bestie. Great for lockers and whiteboards. Put her on the fridge.","keywords":["cute magnet","fridge magnet","breakup gift","petty gift","kitchen decor","villain era decor","aesthetic magnet","heart apple"]},
{"id":"p39","pinTitle":"Bitten Heart Tee — 'Petty Since the Garden' Shirt | Villain Era Breakup Tee 🍎","pinDesc":"The flagship: our bitten heart-apple mascot over PETTY SINCE THE GARDEN — the whole brand in one shirt. This villain era tee is a self-love staple and petty breakup gift for the bestie owning her single era. Great for matching squads and group orders. Wear the whole vibe.","keywords":["villain era outfit","petty quotes shirt","funny breakup shirt","self love tee","breakup gift","matching shirts","aesthetic tshirt","single era"]},
{"id":"p40","pinTitle":"'Villain Era' Tee — Villain Era Outfit Shirt | Petty Breakup Gift, Population: Me 🍎","pinDesc":"Population: me. Lean all the way into your villain era with this soft everyday tee at a petty price. A self-love shirt and breakup gift for the bestie who's done being the nice one. Great for group orders and matching girls'-trip fits. Own your era — add to cart.","keywords":["villain era outfit","villain era shirt","funny breakup shirt","self love tee","petty quotes shirt","matching shirts","group order shirts","single girl gift"]},
{"id":"p41","pinTitle":"'Hot Single Summer' Tee — Hot Girl Summer Shirt | Single Era Beach Gift 🍎","pinDesc":"No exes, no closure, just sun — the uniform of your hot single summer. This hot-girl-summer tee is a single era staple and petty breakup gift for beach trips, girls' getaways, and villain era glow-ups. Great for group orders and matching squads. Suit up for summer — shop it.","keywords":["hot girl summer outfit","hot single summer","single era","funny summer shirt","breakup gift","matching shirts","group order shirts","villain era outfit"]},
{"id":"p42","pinTitle":"'Touch Grass' Tee — Funny Meme Shirt | Petty Breakup Gift for Him or Her 🍎","pinDesc":"Touch grass, not my ex — a public service announcement you can wear. This funny meme shirt is a petty gift and villain era staple for the bestie who's terminally online and unbothered. Great for group orders and matching squads. Say it without saying it. Add to cart.","keywords":["funny meme shirt","touch grass","petty quotes shirt","funny breakup shirt","villain era outfit","matching shirts","group order shirts","gift for single friend"]},
{"id":"p44","pinTitle":"adamnot♥eve Logo Tee (Value) — Cheap Matching Shirts | Group Order Breakup Tee 🍎","pinDesc":"Wear the brand for less — the adamnot♥eve wordmark on a soft, affordable Gildan tee. Built for group orders and matching squads on a girls' trip, bachelorette, or divorce party. A budget villain era staple and petty breakup gift. Stock up the crew — add to cart.","keywords":["matching shirts","group order shirts","cheap tshirts bulk","villain era outfit","breakup gift","bachelorette shirts","affordable tshirt","self love tee"]},
{"id":"p45","pinTitle":"Bitten Heart Tee (Value) — 'Petty Since the Garden' Group Order Shirt | Cheap Petty Tee 🍎","pinDesc":"Our flagship mascot, wallet-friendly: the bitten heart-apple + 'Petty Since the Garden' on a soft, affordable Gildan tee. Perfect for group orders, matching squads, and divorce or single-summer parties. A budget villain era staple and petty breakup gift. Outfit the whole crew.","keywords":["matching shirts","group order shirts","cheap tshirts bulk","villain era outfit","petty quotes shirt","breakup gift","affordable tshirt","bachelorette shirts"]},
{"id":"p43","pinTitle":"'Villain Era' Sticker — Population: Me Sticker | Petty Laptop Water Bottle Sticker 🍎","pinDesc":"Your villain era, die-cut. Population: me — slap it on a laptop, journal, or water bottle. This petty breakup sticker is a tiny self-love gift and villain era accessory for the bestie done playing nice. Cute weatherproof and quietly savage. Claim your era — stick it on.","keywords":["villain era sticker","funny sticker","laptop sticker","water bottle sticker","petty quotes","breakup sticker","aesthetic stickers","villain era"]},
{"id":"p46","pinTitle":"'Hot Single Summer' Tank Top — Hot Girl Summer Tank | Single Era Beach Gift 🍎","pinDesc":"No exes, no closure, just sun. Hot Single Summer on a soft jersey tank — the uniform for beach days, girls' trips, and villain era glow-ups. A single era staple and petty breakup gift for the freshly single bestie. Great for hot-girl-summer fits. Tank up for summer.","keywords":["hot girl summer outfit","hot single summer","tank top aesthetic","single era","breakup gift","summer outfit","villain era outfit","gift for single friend"]},
{"id":"p48","pinTitle":"'Manifest Don't Text' Mouse Pad — Aesthetic Desk Decor | Self Care Office Gift 🍎","pinDesc":"Manifest, don't text — right under your mouse. This full-color mouse pad (8.7 x 7.1 in) is aesthetic desk decor, a self-care office gift, and petty breakup pick-me-up for the WFH bestie. Great for cute desk setups and villain era workspaces. Upgrade your desk — add to cart.","keywords":["aesthetic mouse pad","cute desk setup","home office aesthetic","breakup self care","self care gift","villain era decor","desk accessories","office gift"]},
{"id":"p50","pinTitle":"'Petty Since the Garden' Throw Blanket — Cozy Villain Era Decor | Self Care Gift 🍎","pinDesc":"Cozy up in your villain era with a soft 'Petty Since the Garden' throw blanket. This aesthetic room decor doubles as breakup self-care and a petty gift for the freshly single bestie's couch. Great for reading nooks and sad-girl movie nights. Wrap up and heal — add to cart.","keywords":["throw blanket aesthetic","aesthetic room decor","breakup self care","villain era decor","cozy blanket gift","self care gift","petty gift","gift for single friend"]},
{"id":"p52","pinTitle":"Petty Pin Set (5) — Funny Enamel Pins | Villain Era Breakup Accessory 🍎","pinDesc":"Five petty buttons — bitten apple, Red Flag Club, Petty, Emotionally Unavailable, and Blocked. This funny pin set is a villain era accessory, tote-and-jacket flair, and petty breakup gift for the bestie who wears her attitude. Great stocking stuffer. Pin your era on.","keywords":["funny pins","enamel pin set","villain era accessory","petty gift","breakup gift","aesthetic pins","backpack pins","gift for single friend"]},
{"id":"p53","pinTitle":"'Hot Single Summer' Beach Towel — Single Era Beach Gift | Aesthetic Pool Towel 🍎","pinDesc":"No exes, no closure, just sun. This big, soft Hot Single Summer beach towel is a single era essential, aesthetic pool accessory, and petty breakup gift for beach trips and girls' getaways. Great for villain era summer content. Claim your spot in the sand — add to cart.","keywords":["hot girl summer","beach towel aesthetic","single era","summer beach gift","breakup gift","villain era","pool accessories","gift for single friend"]},
{"id":"p54","pinTitle":"Petty Bucket Hat — Reversible Bitten Apple Bucket Hat | Villain Era Summer Accessory 🍎","pinDesc":"All-over apples, all attitude — a reversible bucket hat covered in the bitten heart. This villain era accessory is a hot single summer staple and petty breakup gift for festivals, beach days, and bad-hair glow-ups. Great for matching-squad summer content. Top off your fit.","keywords":["bucket hat aesthetic","villain era accessory","hot single summer","festival outfit","petty gift","summer accessories","breakup gift","reversible bucket hat"]},
{"id":"p55","pinTitle":"'Petty Since the Garden' Throw Pillow — Villain Era Room Decor | Aesthetic Couch Pillow 🍎","pinDesc":"Decor with a vendetta: a soft 'Petty Since the Garden' throw pillow for the couch you now have to yourself. This aesthetic room decor is breakup self-care and a petty gift for the freshly single bestie's glow-up apartment. Great for housewarmings. Throw it on — add to cart.","keywords":["throw pillow aesthetic","aesthetic room decor","villain era decor","breakup self care","housewarming gift","self care gift","petty gift","gift for single friend"]},
{"id":"p56","pinTitle":"'Block. Delete. Thrive.' Poster — Self Love Wall Art | Breakup Affirmation Print 🍎","pinDesc":"Daily affirmation for the wall: BLOCK. DELETE. THRIVE. This museum-matte poster is self-love wall art, aesthetic room decor, and a petty breakup gift for the bestie's healing-era gallery wall. Great for dorms and glow-up apartments. Hang your mantra — add to cart.","keywords":["self love wall art","aesthetic room decor","breakup affirmation","villain era decor","motivational poster","breakup self care","petty gift","dorm decor"]},
{"id":"p57","pinTitle":"'Come Outside' Tee (Value) — Funny Meme Shirt | Group Order Petty Gift 🍎","pinDesc":"Stick-figure scuffle + 'Come outside, we not gonna jump you.' This funny meme shirt on a soft, affordable Gildan tee is built for group orders and matching squads. A petty villain era staple and gift for the bestie with jokes. Great for girls' trips. Stock up the crew.","keywords":["funny meme shirt","group order shirts","matching shirts","cheap tshirts bulk","petty quotes shirt","villain era outfit","funny gift","affordable tshirt"]},
{"id":"p58","pinTitle":"'Busy Healing' Tee (Value) — Self Love Shirt | Group Order Breakup Gift 🍎","pinDesc":"'You called? I was busy healing.' This self-love meme shirt on a soft, affordable Gildan tee is a petty breakup gift and villain era staple — built for group orders and matching squads. Great for girls' trips and healing-era besties. Heal loud, buy cheap. Add to cart.","keywords":["self love tee","funny breakup shirt","group order shirts","matching shirts","healing era","petty quotes shirt","cheap tshirts bulk","villain era outfit"]},
{"id":"p59","pinTitle":"'Blocked. Blessed. Booked.' Tee (Value) — Petty Affirmation Shirt | Group Order Gift 🍎","pinDesc":"'Blocked. Blessed. Booked.' — the mantra, on a soft, affordable Gildan tee. This petty affirmation shirt is a villain era staple and self-love gift built for group orders and matching squads. Great for girls' trips and glow-up besties. Manifest in bulk — add to cart.","keywords":["petty quotes shirt","self love tee","group order shirts","matching shirts","villain era outfit","funny breakup shirt","cheap tshirts bulk","affirmation shirt"]},
{"id":"p60","pinTitle":"'We Don't Chase, We Replace' Tee (Value) — Petty Breakup Shirt | Group Order Gift 🍎","pinDesc":"'We don't chase, we replace.' This petty breakup shirt on a soft, affordable Gildan tee is a villain era staple and self-love gift built for group orders and matching squads. Great for girls' trips and unbothered besties. Say it in bulk — stock up the crew.","keywords":["petty quotes shirt","funny breakup shirt","villain era outfit","group order shirts","matching shirts","self love tee","cheap tshirts bulk","single era"]},
{"id":"p61","pinTitle":"'Not My Fault You Fumbled' Tee (Value) — Petty Ex Shirt | Group Order Breakup Gift 🍎","pinDesc":"'Not my fault you fumbled.' This petty ex-callout shirt on a soft, affordable Gildan tee is a villain era staple and funny breakup gift built for group orders and matching squads. Great for girls' trips and confident besties. Remind him in bulk — add to cart.","keywords":["petty quotes shirt","funny breakup shirt","villain era outfit","group order shirts","matching shirts","self love tee","cheap tshirts bulk","single era"]},
{"id":"p62","pinTitle":"'I'll Ruin My Own Life' Tee (Value) — Funny Sarcastic Shirt | Group Order Petty Gift 🍎","pinDesc":"'Thanks, but I'll ruin my own life.' This funny sarcastic shirt on a soft, affordable Gildan tee is a villain era staple and petty gift built for group orders and matching squads. Great for girls' trips and self-sabotage-with-style besties. Buy in bulk — add to cart.","keywords":["funny sarcastic shirt","petty quotes shirt","villain era outfit","group order shirts","matching shirts","funny breakup shirt","cheap tshirts bulk","self love tee"]},
{"id":"p63","pinTitle":"'I'm Not Arguing, I'm Just Right' Tee (Value) — Funny Sassy Shirt | Group Order Gift 🍎","pinDesc":"'I'm not arguing, I'm just right.' This funny sassy shirt on a soft, affordable Gildan tee is a petty villain era staple built for group orders and matching squads. Great for girls' trips and always-right besties. Win the argument in bulk — stock up the crew.","keywords":["funny sassy shirt","petty quotes shirt","villain era outfit","group order shirts","matching shirts","funny breakup shirt","cheap tshirts bulk","sarcastic tshirt"]},
{"id":"p64","pinTitle":"'I Said What I Said' Tee (Value) — Petty Sassy Shirt | Group Order Breakup Gift 🍎","pinDesc":"'I said what I said.' This petty sassy shirt on a soft, affordable Gildan tee is a villain era staple and funny gift built for group orders and matching squads. Great for girls' trips and unapologetic besties. No takebacks, in bulk. Add to cart.","keywords":["petty quotes shirt","funny sassy shirt","villain era outfit","group order shirts","matching shirts","funny breakup shirt","cheap tshirts bulk","self love tee"]},
{"id":"p65","pinTitle":"'Petty Committee: President' Tee (Value) — Funny Petty Shirt | Group Order Gift 🍎","pinDesc":"'Petty Committee: President.' This funny petty shirt on a soft, affordable Gildan tee is a villain era staple and breakup gift built for group orders and matching squads. Great for girls' trips and the pettiest bestie in the chat. Elect the crew in bulk — add to cart.","keywords":["funny petty shirt","petty quotes shirt","villain era outfit","group order shirts","matching shirts","funny breakup shirt","cheap tshirts bulk","gift for best friend"]},
{"id":"p66","pinTitle":"'Delulu Is the Solulu' Tee (Value) — Funny Meme Shirt | Group Order Bestie Gift 🍎","pinDesc":"'Delulu is the solulu.' This funny meme shirt on a soft, affordable Gildan tee is a villain era staple and self-love gift built for group orders and matching squads. Great for girls' trips and manifestation besties. Stay delulu in bulk — stock up the crew.","keywords":["funny meme shirt","delulu","petty quotes shirt","villain era outfit","group order shirts","matching shirts","cheap tshirts bulk","self love tee"]},
{"id":"p67","pinTitle":"'Loyal to the Group Chat' Tee (Value) — Funny Bestie Shirt | Group Order Gift 🍎","pinDesc":"'Loyal to the group chat.' This funny bestie shirt on a soft, affordable Gildan tee is a villain era staple and best-friend gift built for group orders and matching squads. Great for girls' trips, bachelorettes, and the ride-or-die chat. Outfit the crew — add to cart.","keywords":["funny bestie shirt","group order shirts","matching shirts","best friend gift","villain era outfit","petty quotes shirt","cheap tshirts bulk","bachelorette shirts"]},
{"id":"p68","pinTitle":"'I'm Healing But Don't Push Me' Tee — Funny Mental Health Shirt | Villain Era Gift 🍎","pinDesc":"'I'm healing, but don't push me.' A funny mental-health & self-love tee for your healing era — petty, soft, and honest. Great breakup gift for a bestie in her villain era, and a value Gildan built for group orders and matching squads. Heal loud — add to cart.","keywords":["funny mental health shirt","self love tee","healing era","villain era outfit","breakup gift","petty quotes shirt","group order shirts","gift for best friend"]},
{"id":"p69","pinTitle":"'Pain Is Temporary, Regret Is Forever' Tee — Motivational Petty Shirt | Breakup Gift 🍎","pinDesc":"'Pain is temporary, regret is forever.' A bold motivational-meets-petty tee for the villain era and no-regrets bestie. Funny breakup gift on a soft value Gildan — built for group orders and matching squads. Wear the reminder — add to cart.","keywords":["motivational shirt","petty quotes shirt","funny breakup shirt","villain era outfit","breakup gift","self love tee","group order shirts","matching shirts"]},
{"id":"p70","pinTitle":"'Single. Taken. Complicated.' Tee — Funny Relationship Status Shirt | Petty Gift 🍎","pinDesc":"Single. Taken. Complicated — checkbox says it all. A funny relationship-status tee for the situationship era and unbothered bestie. Petty breakup gift on a soft value Gildan, built for group orders and matching squads. Check your mood — add to cart.","keywords":["funny relationship shirt","situationship","petty quotes shirt","funny breakup shirt","villain era outfit","group order shirts","matching shirts","gift for single friend"]},
{"id":"p71","pinTitle":"'Be Loyal Behind My Back' Tee — Funny Front & Back Petty Shirt | Breakup Gift 🍎","pinDesc":"Front: 'Wanna impress me? Be loyal…' Back: '…behind my back.' A funny two-sided petty tee that hits twice. Villain era staple and savage breakup gift on a soft value Gildan — built for group orders and matching squads. Flex both sides — add to cart.","keywords":["funny petty shirt","front and back shirt","villain era outfit","funny breakup shirt","loyalty quotes","group order shirts","matching shirts","petty quotes shirt"]},
{"id":"p72","pinTitle":"'I'm Not a Backup Plan, I'm the Upgrade' Tee — Self Worth Shirt | Villain Era Gift 🍎","pinDesc":"'I'm not a backup plan — I'm the upgrade.' Pure villain-era confidence and self-worth for the bestie who knows her value. Petty breakup gift on a soft value Gildan, built for group orders and matching squads. Know your worth — add to cart.","keywords":["self worth shirt","villain era outfit","confidence shirt","funny breakup shirt","self love tee","petty quotes shirt","group order shirts","gift for best friend"]},
{"id":"p73","pinTitle":"'I Hope She's Worth the Downgrade' Tee — Savage Breakup Shirt | Petty Ex Gift 🍎","pinDesc":"'I hope she's worth the downgrade.' The pettiest mic-drop for your villain era — savage, funny, and unbothered. A breakup gift for the bestie who upgraded herself, on a soft value Gildan built for group orders and matching squads. Say it louder — add to cart.","keywords":["savage breakup shirt","funny breakup shirt","petty quotes shirt","villain era outfit","ex boyfriend gift","self love tee","group order shirts","matching shirts"]},
{"id":"p74","pinTitle":"'He's a Lesson, Not a Loss' Tee — Self Love Breakup Shirt | Healing Era Gift 🍎","pinDesc":"'He's a lesson, not a loss.' Closure you can wear — a self-love and healing-era tee for the bestie moving on and leveling up. Petty breakup gift on a soft value Gildan, built for group orders and matching squads. Rewrite the story — add to cart.","keywords":["self love tee","healing era","funny breakup shirt","villain era outfit","breakup gift for her","petty quotes shirt","group order shirts","gift for best friend"]},
{"id":"p75","pinTitle":"'Still a Catch, You Just Can't Fish' Tee — Funny Fishing Breakup Shirt | Petty Gift 🍎","pinDesc":"'Still a catch — you just can't fish.' A funny fishing-pun breakup tee (with a lil fisherman) for the confident, unbothered bestie. Petty gift on a soft value Gildan, built for group orders and matching squads. Reel in the compliments — add to cart.","keywords":["funny fishing shirt","funny breakup shirt","petty quotes shirt","villain era outfit","pun shirt","self love tee","group order shirts","gift for single friend"]},
{"id":"p76","pinTitle":"'My Silence Is Your Closure' Tee — Cold Petty Breakup Shirt | Villain Era Gift 🍎","pinDesc":"'My silence is your closure.' Ice-cold and unbothered — the villain-era mantra for the bestie who blocked and moved on. Savage breakup gift on a soft value Gildan, built for group orders and matching squads. Go silent — add to cart.","keywords":["savage breakup shirt","villain era outfit","petty quotes shirt","funny breakup shirt","no contact","self love tee","group order shirts","matching shirts"]},
{"id":"p77","pinTitle":"'Deleted Him, Downloaded Peace' Tee — Funny Self Love Breakup Shirt | Healing Gift 🍎","pinDesc":"'Deleted him, downloaded peace.' The glow-up in one line — a funny self-love and healing-era tee for the bestie who chose herself. Petty breakup gift on a soft value Gildan, built for group orders and matching squads. Update your life — add to cart.","keywords":["funny breakup shirt","self love tee","healing era","villain era outfit","petty quotes shirt","glow up","group order shirts","gift for best friend"]},
{"id":"p78","pinTitle":"'I Survived a Narcissist and I'm Still Standing' Tee — Narcissist Survivor Shirt | Healing Gift 🍎","pinDesc":"'I survived a narcissist and I'm still standing.' A survivor anthem and self-love tee for narcissistic-abuse recovery and the healing era. A meaningful, empowering gift on a soft value Gildan, built for group orders and support squads. Stand tall — add to cart.","keywords":["narcissist survivor shirt","narcissistic abuse recovery","self love tee","healing era","mental health shirt","survivor gift","breakup gift","empowerment shirt"]}
];

const PIN_SEO = {};
for (const e of PIN_SEO_LIST) PIN_SEO[e.id] = e;

module.exports = { PIN_SEO };
